# This docker image is for development only so that there will be no version conflicts
FROM golang:1.10.3-stretch
MAINTAINER Harry Lee

RUN apt-get update && apt-get install curl -y

RUN curl https://glide.sh/get | sh

RUN useradd --create-home --shell /bin/bash 1000
RUN chown -R 1000 /go

USER 1000
